# Generated by Django 5.2.7 on 2025-11-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Fashion Store', max_length=255)),
                ('store_email', models.EmailField(default='info@fashionstore.com', max_length=254)),
                ('store_phone', models.CharField(default='+57 300 123 4567', max_length=50)),
                ('store_address', models.TextField(default='Cienaga Magdalena, Colombia')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('enable_nequi', models.BooleanField(default=True)),
                ('enable_stripe', models.BooleanField(default=False)),
                ('enable_mercadopago', models.BooleanField(default=False)),
                ('enable_contra_entrega', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('free_shipping_min', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tienda',
            },
        ),
    ]
