# Generated by Django 5.2.7 on 2025-11-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_color',
            field=models.CharField(default='#3B82F6', help_text='Código de color hexadecimal (ej: #3B82F6)', max_length=7),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Imagen para el banner (máx 5MB)', null=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_type',
            field=models.CharField(choices=[('color', 'Color de Fondo'), ('image', 'Imagen Personalizada')], default='color', max_length=10),
        ),
    ]
