# Generated by Django 5.2.7 on 2025-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeconfiguration_banner_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='footer_background_color',
            field=models.CharField(default='#1F2937', help_text='Color de fondo del footer (código hexadecimal)', max_length=7),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='footer_text_color',
            field=models.CharField(default='#D1D5DB', help_text='Color del texto del footer (código hexadecimal)', max_length=7),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='footer_title_color',
            field=models.CharField(default='#FFFFFF', help_text='Color de los títulos del footer (código hexadecimal)', max_length=7),
        ),
    ]
