# Generated by Django 5.2.7 on 2025-11-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_footer_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_text',
            field=models.TextField(default='Bienvenido a MONASTERY\nLas mejores tendencias en moda al mejor precio', help_text='Texto principal del banner (usar \\n para salto de línea)'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Color del texto del banner (código hexadecimal)', max_length=7),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='enable_banner_offers_button',
            field=models.BooleanField(default=True, help_text='Mostrar botón "Ver ofertas" en el banner'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='enable_banner_products_button',
            field=models.BooleanField(default=True, help_text='Mostrar botón "Ver productos" en el banner'),
        ),
    ]
