# Generated by Django 5.2.7 on 2025-11-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_banner_text_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='enable_banner_offers_button',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='enable_banner_products_button',
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_subtitle_text',
            field=models.CharField(default='Las mejores tendencias en moda al mejor precio', help_text='Texto secundario del banner', max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='banner_title_text',
            field=models.CharField(default='Bienvenido a Fashion Store', help_text='Texto principal del banner', max_length=255),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='enable_offers_button',
            field=models.BooleanField(default=True, help_text='Mostrar botón de Ver Ofertas'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='enable_products_button',
            field=models.BooleanField(default=True, help_text='Mostrar botón de Ver Productos'),
        ),
    ]
